version: "3"

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - drupal_network

  mydrupal:
    build: .
    container_name: drupal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - drupal_network
    volumes:
      - drupal-data:/var/www/html

networks:
  drupal_network:
    driver: bridge

volumes:
  drupal-data:
  db-data:
